### ISSUE TITLE
call_with_depth_limit/3: Once you run it with a negative limit on the toplevel, it seems to not go away?

### ISSUE THREAD

**Issue by dtonhofer** [SWI-Prolog/swipl-devel#751] opened 2020-12-23 12:58 UTC
I was just testing call_with_depth_limit/3 

Once this happens:

```
?- call_with_depth_limit(true,-1,Max).
Recursive query message: query(no)
```

it seems as if the limiter is not cleared?

```
?- call_with_depth_limit(true,10,Max).
Recursive query message: query(no)
```

**Comment by JanWielemaker** [comment] 2020-12-23 13:40
Thanks.  Should be fixed with 178bf0ce0c735c2afef6b840601da9473afaf744.  This patch cleans up types involved in depth limiting.  This issue was caused by DEPTH_NO_LIMIT conflicting with -1.

**Closed by JanWielemaker** 2020-12-23 13:40 UTC

**Comment by dtonhofer** [comment] 2020-12-23 14:23
Awesome. How can you code so quickly?

**Comment by JanWielemaker** [comment] 2020-12-23 14:33
By using users such as you as guinea pig? :smile:  And of course by having an ever growing test set that quite often complains when I mess things up.   Part of that was also supplied by users or the result of some bug report.
