### ISSUE TITLE
Bug in tuples_in/2 of CLP(FD)

### ISSUE THREAD

**Issue by leuschel** [SWI-Prolog/swipl-devel#1160] opened 2023-04-11 12:59 UTC
According to my understanding of tuples_in/2 this behaviour is not correct:
```
?- tuples_in([[A,B]],[[11,0],[12,1]]), tuples_in([[A,B]],[[12,0],[13,1]]).
A = 12,
B = 1.
?- tuples_in([[A,B]],[[11,0],[12,2]]), tuples_in([[A,B]],[[12,0],[13,1]]).
A = 12,
B = 2.
```

Funnily enough, here it corresponds to my understanding:
```
?- tuples_in([[A,B]],[[11,0],[12,2]]), tuples_in([[A,B]],[[12,1],[13,1]]).
false.
```

**Comment by leuschel** [comment] 2023-04-11 13:05
Version info:
$ swipl --version
SWI-Prolog version 9.0.3 for fat-darwin

**Comment by JanWielemaker** [comment] 2023-04-11 13:14
Reproduces in the latest version (not a surprise, clp(fd) didn't change).   If I read the docs correctly, you are right.   @triska, would you agree?

**Comment by leuschel** [comment] 2023-04-11 13:18
Here another example, maybe it helps detecting the issue:
```
?- tuples_in([[A,B]],[[13,10],[122,2]]), tuples_in([[A,B]],[[13,2]]).
A = 13,
B = 10.
```

**Comment by leuschel** [comment] 2023-04-11 17:30
Note that the wrong solution remains even after labeling is done; I would not expect that CLP(FD) has pending co-routines after labeling:
```
?- tuples_in([[A,B]],[[13,10],[12,2]]), tuples_in([[A,B]],[[13,2]]), labeling([],[A,B]).
A = 13,
B = 10.
```
Also note that ProB uses call_residure_vars to detect pending co-routines and create a warning. However, this did not seem be triggered (in the initial more complex context where I first uncovered the bug).

**Comment by triska** [comment] 2023-04-11 17:34
The SWI-Prolog toplevel does not show all pending constraints. For comparison, with Scryer Prolog:

<pre>
<b>?- tuples_in([[A,B]],[[13,10],[12,2]]), tuples_in([[A,B]],[[13,2]]), labeling([],[A,B]).</b>
   A = 13, B = 10, clpz:put_atts(_A,clpz_relation([[13,10],[12,2]])), clpz:put_atts(_B,clpz_relation([[13,2]])).
</pre>

So, a conditional answer.

**Comment by leuschel** [comment] 2023-04-11 17:37
I guess there are some existentially quantified internal variables that are not labelled:
```
?- call_residue_vars((tuples_in([[A,B]],[[13,10],[12,2]]), tuples_in([[A,B]],[[13,2]]), labeling([],[A,B])),CV).
A = 13,
B = 10,
CV = [_, _].
```
Note in SICStus we get 
```
| ?- table([[A,B]],[[13,10],[12,2]]).
A in 12..13,
B in{2}\/{10} ? 
yes
| ?- table([[A,B]],[[13,10],[12,2]]), table([[A,B]],[[13,2]]).
no
```

**Comment by triska** [comment] 2023-04-11 20:34
I think I addressed this in https://github.com/mthom/scryer-prolog/pull/1780/commits/5dce7d907572f7646a26214f129c9200340939f7. 

The key change is that `Firsts = [Unique] -> T = Unique` is performed under all circumstances (not only if `T` is a variable).

If possible, could you please try the analogous change with `clpfd.pl`, and see how that works?

**Comment by triska** [comment] 2023-04-12 18:22
> Is there any danger applying this?

Personally, I think it is OK to apply it! The main open question is whether there are other cases where `tuples_in/2` can be rightfully expected to propagate more strongly. So, if anyone finds such issues, please do report them.

> It was always my understanding that a well-behaved constraint program does not leave residual variables behind that are > not reachable from its arguments and call_residue_vars/2 is (thus) only required for debugging purposes. Is that wrong?

If we expect the key invariant of a Prolog toplevel to hold, i.e., that answers are declaratively equivalent to queries, then we **must** use `call_residue_vars/2` by default so that *all* pending constraints are reliably reported in all&nbsp;cases. One of the simplest programs to test this is:

<pre>
p :- freeze(_, false).
</pre>

A correct Prolog toplevel, such as the one provided by Scryer or SICStus Prolog, yields for example:

<pre>
<b>?- p.</b>
   freeze:freeze(_A,false).
</pre>

The most important feature of a toplevel is arguably that it yields correct results. You may want to provide a flag to disable correct behaviour, so that wrong answers are computed very efficiently.

**Comment by JanWielemaker** [comment] 2023-04-12 19:22
> Personally, I think it is OK to apply it!

Thanks.  Done.

> SICStus Prolog, yields for example:

Not my copy (4.6.0) :smile:    I have my doubt about this.    In my view a program that introduced constraints that are never triggered is buggy.    Printing these is useful for debugging.    `debug' mode is also useful for debugging, but we do not enable it by default because it makes the program behave different wrt. resource usage (time and space).   It could be an option to enable printing residuals by default when the toplevel is in debug mode.   Surely the impact of wrapping in `call_residue_vars/2` is way smaller than that of `debug` mode.

Closing this issue as the problem reported is fixed.

**Closed by JanWielemaker** 2023-04-12 19:22 UTC

**Comment by UWN** [comment] 2023-04-12 19:54
>Not my copy (4.6.0)

Both 4.4.1 and 4.8 :
```
| ?- [user].
% compiling user...
| p:-freeze(_,false).
| 
% compiled user in module user, 129 msec 549456 bytes
yes
| ?- p.
prolog:freeze(_A,user:false) ? 
yes
```

**Comment by UWN** [comment] 2023-04-12 20:49
@leuschel: As a general observation, consider using `clpz` with SICStus, which gives about a 3fold speedup compared to SWI. SICStus supports the same atv-interface as Scryer. In fact, SICStus was the origin of atvs.
