### ISSUE TITLE
Type error: `character_code' expected, found `-1' (an integer)

### ISSUE THREAD

**Issue by motobuzz** [SWI-Prolog/swipl-devel#245] opened 2017-06-20 08:02 UTC
An error occurs in the top-level on any keypress when a query has several solutions. It does not matter whether I consult a file or add facts with assert. 

An example dialog with the top-level:

```
1 ?- dynamic(person/1).
true.

2 ?- assert(person(a)).
true.

3 ?- assert(person(b)).
true.

4 ?- person(X).
X = a                                                    <-------------------- a key is pressed here
ERROR: Type error: `character_code' expected, found `-1' (an integer)
ERROR: In:
ERROR:   [11] char_code(_6408,-1)
ERROR:   [10] '$in_reply'(-1,'?h') at z:/swipl/boot/init.pl:797
```

The issue is reproducible only with swipl.exe and not with swipl-win.exe.

I have tried the following versions: swipl-w32-742.exe, swipl-w64-742.exe, swipl-w64-2017-06-20.exe.

I have Windows 10, version 1703, build 15063.413. The issue might be related to the latest Windows update because I have had no any problem before updating from 1607.

**Comment by JanWielemaker** [comment] 2017-06-20 08:19
I assume this implies that `get_single_char(C)` returns always `C = -1`?

**Comment by motobuzz** [comment] 2017-06-20 08:56
Yes, it does.

```
1 ?- get_single_char(C).
C = -1.

2 ?- get_single_char(C).
C = -1.

2 ?- get_single_char(C).
C = -1.
```

**Comment by wouterbeek** [comment] 2017-07-02 19:01
I can reproduce this (Windows 10, latest nightly build of SWI).

What's the difference between `swipl.exe` and `swipl-win.exe`?  Is the former intended for running in a terminal and the latter for running in a GUI window?

**Comment by thetrime** [comment] 2017-07-24 04:18
I can't reproduce this in win10 build 10240, but my colleague can with build 15063.483. I'll see if I can find a spare machine with a later version of win10 on it

**Comment by thetrime** [comment] 2017-07-24 23:59
It also reproduces in 15063.0

**Comment by thetrime** [comment] 2017-07-25 03:00
This seems to be a change in the behaviour of ReadConsole. It returns success but reports reading 0 bytes. Changing the code to loop until at least one character is read or ReadConsole returns 0 appears to solve the problem, but I'm not sure if that's a good idea or not (yet)

**Comment by thetrime** [comment] 2017-07-25 04:40
It would appear to have something to do with PL_wait_for_console_input(). I wonder if SetConsoleMode followed by PL_wait_for_console_input() is consuming the first ; character somehow in new builds of Windows 10? In any case, commenting out the call to PL_wait_for_console_input() makes the symptoms go away.

**Comment by thetrime** [comment] 2017-08-18 05:30
This is a simple test case:

```
#include <windows.h>
#include <stdio.h>

int main()
{
   BOOL rc;
   HANDLE hConsole = GetStdHandle(STD_INPUT_HANDLE);
   DWORD mode;
   DWORD done;
   char* buffer = malloc(128);
   size_t size = 32;

   GetConsoleMode(hConsole, &mode);
   SetConsoleMode(hConsole,
                  mode & ~(ENABLE_LINE_INPUT|ENABLE_ECHO_INPUT));
   rc = MsgWaitForMultipleObjects(1,
                                  &hConsole,
                                  FALSE,	/* wait for either event */
                                  INFINITE,
                                  QS_ALLINPUT);
   printf("Result 1: %d\n", rc);
   rc = ReadConsoleW(hConsole,
                     buffer,
                     (DWORD)(size / sizeof(wchar_t)),
                     &done,
                     NULL);
   printf("Result 2: %d, done: %d, buffer[0]: %d\n", rc, done, buffer[0]);
}
```

On win7 I get: 
```
Result 1: 0
Result 2: 1, done: 1, buffer[0]: 97
```
On win10 I get:
```
Result 1: 0
Result 2: 1, done: 0, buffer[0]: 97
```

I can't find any explanation in the MSDN about what might have changed, but since I have a smallish test case I thought I'd better save it *somewhere* at least

**Comment by JanWielemaker** [comment] 2017-08-18 06:59
This looks like a clear bug to me.   Considering this fetches a single char, can't we do as follows:

  - zero the output buffer before calling `ReadConsoleW`
  - If `done` is 0, set it to the number of non-zero chars in the output buffer

And, if you are really brave, report with MS ...  Might work if you have a developer license.

**Comment by JanWielemaker** [comment] 2017-08-30 10:56
Pushed 16419953148b595c290aef778aabb954493fcb73 to implement the above hack.   I don't know whether it will help, but I can't do much harm either.  Please check (tomorrows daily build or 7.5.14).

**Comment by motobuzz** [comment] 2017-08-31 05:49
I can confirm that I cannot reproduce the issue with swipl-w64-2017-08-31.

**Comment by JanWielemaker** [comment] 2017-08-31 06:59
Thanks.  I close it.  Hope that will be final ...

**Closed by JanWielemaker** 2017-08-31 06:59 UTC
Labels: Platform: Windows
