### ISSUE TITLE
float_parts predicate isn't true to the IEEE 754 standard for fp data representation

### ISSUE THREAD

**Issue by yoquierotacob** [SWI-Prolog/swipl-devel#934] opened 2022-01-27 09:04 UTC
SWI-Prolog (threaded, 64 bits, version 8.4.1) on Windows 10

Per Swi-prolog, documentation  your recently added float_parts predicate  uses or is based on  the frexp()  C library function.  
https://www.swi-prolog.org/pldoc/doc_for?object=float_parts/4

The problem  here is that frexp is  not true to IEEE 754 fp data representation standard.   There may a reasonable explanation behind frexp()'s particular implementation, but to that I am not privy.   After a plain reading of the IEEE 754 standard, I think frexp()'s implementation just does not  jibe with it.  Find  IEEE  754 description and tools here:

https://en.wikipedia.org/wiki/Double-precision_floating-point_format
https://www.binaryconvert.com/convert_double.html#
http://sandbox.mc.edu/~bennet/cs110/flt/dtof.html

Using a simple example of using 15.1234, swi-prolog's float_parts gives:
    ?- float_parts(15.1234, Mantissa, Base, Exponent).
    Mantissa = 0.9452125,
    Base = 2,
    Exponent = 4.

And in swi-prolog's documentation, it states: 
  " The following relation is always true:
   Float =:= Mantissa × Base^Exponent"

This math indeed holds, but it is not consistent  with the stardard  fp  data representation which dictates this formula:
   Float =:= (1 + Mantissa) x Base^Exponent  (where Base is 2).

I have written my own  version  of float_parts, per my understanding of IEEE 754:
   ?- my_float_parts(15.1234, Mantissa, Base, Exponent),
    Mantissa = 0.890425,
    Base = 2,
    Exponent = 3
    F is (1 + Mantissa) *(Base**Exponent),

    F = 15.1234.

Comparing the two float_parts predicates, notice that both the computed exponents and the mantissas differ.    To explain how I compute my exponent, I first arrive at the 11-bit exponent as follows (which by the way is consistent with the fp computation tool listed above):
     Exp = [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]

In decimal, this computes to 1026, and per IEEE 754, to get the actual exponent you subtract 1023: 
    1026 - 1023 = 3.

As for the Mantissa, I arrive at a 52-bit mantissa  as follows (again  consistent with the  fp computation tool above):
      Mant = [1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0]

In decimal, this computes to 0.890425.

So you may have a good reason to go with the C frexp() function, and choose to stick with it.  But if not, I am happy to donate my code to  Swi-prolog open source, should you want it.   My float_parts predicate is a lot more verbose and inefficient than it needs to be because I don't have access to the actual 1's and 0s in your floating-point data, but my code could be easily be massaged to work with your fp internals.   Furthermore, I have predicates that break an FP into its 3  constituents (sign, exponent, mantissa) as bit lists (as demonstrated above) for both fp64  and fp32. Also, I have predicates to convert FPs into a bin-hex atom format, e.g. in our example above 
15.1234 -> '0x402E3F2E48E8A71E'

Let me know,
Donald Maffly 
dmaffly@hotmail.com

**Comment by JanWielemaker** [comment] 2022-01-27 09:33
Thanks for your observations.  I'm not much of a float expert.   @ridgeworks, what is your opinion on these matters?

**Comment by ridgeworks** [comment] 2022-01-27 15:44
@yoquierotacob 's analysis is correct: `float_parts/4` uses the `frexp` function from C which, I assume, is defined in the ISO-C standard and therefore unlikely to change. It appears this is not the same higher level representation as IEEE 754 (i.e., same bit level value would yield different mantissa and exponent values), so there is an issue of competing standards. 

The current `float_parts/4` is implemented and documented correctly (according to ISO-C). But it should probably not be in [4.27.2.4 IEEE 754 floating point arithmetic](https://www.swi-prolog.org/pldoc/man?section=ieee-float) . A quick and easy fix would be to change the section title to just "Floating point arithmetic". 

I don't see any particular reason to change what's there, possibly breaking existing code (?), but there may be a justification for adding an IEEE 754  compliant version. It's just that I don't have a particular use case for either one at the moment; maybe Donald has one.

**Comment by yoquierotacob** [comment] 2022-01-28 00:53
@ridgeworks thank you for your attention on this.  You ask for a use case which I give below, But first, I am curious , there must have been an original use case that  would  certainly  also be worth considering.  It might either be flawed in some  way, or it might allow for my proposed change.

My use case is as follows, I am developing an application (using Swi prolog of  course) that interfaces extensively with databases.  So data and moreover  data represenation is  critical.    Particularly, I am converting prolog  data into database data that is suitable to appear in a SQL INSERT statement.   And even more  particularly I am implementing SQL CONVERT(BINARY, <floating point number>)  with the end result being a binary hex atom that might later be appear in a SQL INSERT statement.   So refering  again to my fp number example, I want to  compute CONVERT(BINARY, 15.1234) to   '0x402E3F2E48E8A71E'

If was hoping to  use  a predicate like  float_parts, by taking it's exponent and matissa output, normalizing it by adding 1023 (decimal) to the exp, then deconstructing them both into binary (a list of 1s and 0s), pasting them into a single binary string, then  reconstructing it  into a single bin hex bin atom like the one you see in my example.    Because the current implementation of float_parts is not true to  IEEE 754 standard, I am unable to use it.

In the meantime, I am written a small library of functions that deconstruct integer (e.g. expononent) and decimal (e.g.  a mantissa), into binary strings (lists of 1s and 0s), as well predicates that  can convert these  binary strings into  binhex atoms as well as predicates to convert prolog data (types) values into binhex atoms.  These might  be generally useful to the greater SWI-prolog community.

My need for a float_parts fix is no longer very urgent, but I remain  surprised that nobody else has run into this issue with float_parts.  Perhaps I shouldn't be because, people have been happily coexisting with frexp() for years, not to mention that  the vast majority of prolog applications deal with data only at higher levels of abstraction, and have little need to be bothered with data representation.

**Comment by kamahen** [comment] 2022-01-28 03:08
If you're trying to get the binary form of a float, you could use a foreign function, such as `protobufs:float64_codes/2`:
```
?- use_module(library(protobufs)).
true.

?- protobufs:float64_codes(15.1234, Codes).
Codes = [30, 167, 232, 72, 46, 63, 46, 64].
```
The code is here: https://github.com/SWI-Prolog/contrib-protobufs/blob/master/protobufs.c

BTW, you might have to watch out for big-endian and little-endian (even though little-endian is very dominant)

**Comment by yoquierotacob** [comment] 2022-01-28 07:22
@kamahen Thanks!  There could be a treasure trove for me in protobufs!  After tinkering with it, I've discovered one  small problem.   Those are indeed ASCII codes in decimal, but they are reversed, perhaps  because there is some sort of first-in-last-out thing  going on in this 'wired' context that protobufs was designed for.  

For example,  running protobufs output through hex_bytes, yields: 1ea7e8482e3f2e40' but expect 402E3F2E48E8A71E (ignore case differences, and see that '40' leads in one, and tails in the other).   It is  plain to see that byte order is  reversed, by simply adding a leading negative to our 15.1234 input; per IEEE 754, the sign bit  is in the leading spot in the 64 bit, so we'd expect the  first hex digit to  change but instead it is the last:
?- protobufs:float64_codes(15.1234, Codes).
Codes = [30, 167, 232, 72, 46, 63, 46, 64].

?- protobufs:float64_codes(-15.1234, Codes).
Codes = [30, 167, 232, 72, 46, 63, 46, 192].

Anyway, I can easily reverse it!  Thx for the suggestion!

**Comment by yoquierotacob** [comment] 2022-01-28 08:31
So I've dug deep, deep into an ANSI C standard document (ISO/IEC 9899:201x), and unfortunately, an  implementation  for  frexp() is unequivocally spelled out in stone:
 
double my_frexp(double value, int* exp)
{
     *exp = (value == 0) ? 0 : (int)(1 + logb(value));
     return scalbn(value, -(*exp));
}

I  quickly ran this code through a C compiler, and indeed it delivers the same unexpected result that float_parts does.  :-(

This will require  an act of Congress to change, so I won't bank on any movement on this in the near term, but that won't stop me  from inquiring about it.   If I learn anything interesting, I'll return to document  my findings  here in this  bug report.

**Comment by ridgeworks** [comment] 2022-01-28 16:19
I see you've made progress solving your particular issue, but for the record:

I am unaware of any particular motivating use case for `float_parts/4`. However, all the atomic types have some kind of builtin predicate support for decomposition, e.g., `atom_chars/2` for atoms, `rational/3` for rationals, and various bit-level arithmetic functions for integers, so some predicate to "decompose" floats seems to be warranted. It was probably based `frexp` because it was "low hanging fruit" already available in the C math library (same semantics in Python). And it's probably the most natural semantics for programmers, since it hides all the esoteric details of the IEE 754 bit level representation (e.g., exponent offset, implicit leading 1).

For your use case, it looks like mantissa/exponent values are just an intermediate step to what you really want, i.e., the bit level representation of a Prolog float. For this it would seem to make more sense to go directly to the binary representation as supported by the `protobufs` library as Peter suggests, and which you've already investigated. I did my own little experiment and with the following predicate:
```
codes_hexchars([],[]).
codes_hexchars([C|Cs],[H1,H2|Hs]) :-
	C1 is C div 16, char_type(H1,xdigit(C1)),
	C2 is C mod 16, char_type(H2,xdigit(C2)),
	codes_hexchars(Cs,Hs).
```
you can fairly easily reproduce your earlier result:
```
?- protobufs:float64_codes(15.1234, Codes), reverse(Codes,RCodes), codes_hexchars(RCodes,Hx), atom_chars(A,['0','x'|Hx]).
Codes = [30, 167, 232, 72, 46, 63, 46, 64],
RCodes = [64, 46, 63, 46, 72, 232, 167, 30],
Hx = ['4', '0', '2', e, '3', f, '2', e, '4'|...],
A = '0x402e3f2e48e8a71e'.
```
As you noted the byte values produced by `float64_codes` is reversed. I don't know whether that's an endian issue or something to do with the protobufs spec. Nonetheless it seems to easily address your specific use case.

The only downside is that `float64_codes` isn't an exported public predicate. Not sure if this is a real issue in this case, but maybe it makes sense for someone (Peter?) to create a `protobufs/bin` module with these low level support predicates for use cases like yours. Alternatively, you could just wrap them in your own version of the predicate which avoids qualifying calls with the module name and makes it easier to manage in case they do ever change (probably unlikely).

**Comment by kamahen** [comment] 2022-01-28 18:25
I have no problem with exporting `protobufs:float64_codes/2`, although I wonder if it's the best module for the predicate (not very discoverable). Maybe @JanWielemaker has an opinion?

Protobufs use little-endian encoding on the wire. But not all wire formats use little-endian, so it might make sense to have both little-endian and big-endian versions of the predicate (and named appropriately) -- e.g., network byte order and JPEG use big-endian (integers). Note that the protobufs.c code checks the endian-ness of the processor to ensure that it generates little-endian encodings. (I haven't actually tested this code, because I don't have access to an IBM mainframe or big-endian Power processor - I inherited the code from the original author.)

If you have test cases that you'd like to add, please send them to me, or give me a PR for `test_protobufs.pl`. I'm in the middle of making some changes to accommodate systems that don't have GNU Multiple Precision Arithmetic Library (GMP), but I could probably do some refactoring to separate out `float64_codes/2` et al fairly quickly (or someone could send me a PR).

BTW, the source formatting style in protobufs.c isn't to my taste, but that's what I inherited, so I'm leaving it as-is. There's an `.indent.pro` file that more-or-less matches the formatting style.

**Comment by yoquierotacob** [comment] 2022-01-29 02:05
Thanks  for looking deep into  my problem!  Yes,  so I had already walked throught  the same steps that   @ridgeworks did, and discovered the same  thing.  I don't think it really matters to me whether float64_codes is made public.   I am just happy that it is available!  :-)

**Comment by kamahen** [comment] 2022-01-29 02:27
If `protobufs:float_64_codes` isn't public, you shouldn't depend on it because the maintainer (currently me, but who knows in the future?) isn't under any obligation to keep it.
Let's see what @JanWielemaker says about what to do with it -- merely make it public (possibly with a different name, such as `float_64_codes_little_endian/2`) or move it to some other part of the SWI-Prolog code base.

**Comment by JanWielemaker** [comment] 2022-01-29 17:10
We have been here before :smile:  I don't consider this _decomposition_ of a type, like turning an atom into character codes or one-character atoms, a float into its integral and fractional part etc, testing bits in an integer, etc.  These are all representation independent conversions.   This is about the _representation_ itself.   I don't think the Prolog engine should expose these.   It exposes data to the C interface (which is not necessarily (and quite often not) the Prolog representation).  Of course, in C you can inspect the memory and get representational details.    For floats they are now internally C doubles which on most systems boils down to IEEE 754 representation.  That could change at some point.

Most of this stuff is required for (wire) exchange according to some protocol.  In most cases I'd write the low-level stuff in C(++) as has been done for protobufs, redis and several add-on packs.   It is really easy to do so and often a lot faster as byte level I/O operations in Prolog aren't fast either.

Next to C programming, you can use the [ffi pack](https://www.swi-prolog.org/pack/list?p=ffi) which, besides function calling, can do C memory management (because you need to prepare input and process output).   Getting the memory bytes from a double looks like this:

```
:- use_module(library(ffi)).

:- thread_local
    double_char_pair_cache/3.

double_char_pair(DP, UCharP, Bytes) :-
    double_char_pair_cache(DP, UCharP, Bytes),
    !.
double_char_pair(DP, UCharP, Bytes) :-
    c_alloc(DP, double),
    c_sizeof(double, Bytes),
    c_cast(uchar, DP, UCharP),
    asserta(double_char_pair_cache(DP, UCharP, Bytes)).

double_bytes(F, B1) :-
    double_char_pair(DP, UCharP, Bytes),
    c_store(DP, 0, double, F),
    c_array_to_list(UCharP, Bytes, B1).
```

This gets the same result as the protobufs version mentioned above.   It is slower, on my machine 0.8usec vs. 0.25usec for the protobufs version.

**Comment by ridgeworks** [comment] 2022-01-30 15:50
>  I don't think the Prolog engine should expose these.  ...

And I totally agree. But I do have an issue with:

> It is really easy to do so 

IMO adding C code is never simple. Issues of the C tool chain and platform dependancies introduce added complexity that I avoid at all cost, although I admit there are cases where it's unavoidable.

In this particular case, `protobufs` has done all the heavy C lifting so it seems the issue has boiled down to whether `protobufs` (or some variation) should export the low level predicates so other protocols with similar needs don't have to replicate this good work. Donald seems to be happy with using a non-public version but I would argue it's safer in the long term, and easier to find in docs if at least a selection of the binary level predicates were exported.

BTW, for the record, an even nicer (IMO)  solution using `protobufs` is:
```
?- protobufs:float64_codes(15.1234,Codes), protobufs:int64_codes(I,Codes), format(atom(A),"0x~16r",I).
Codes = [30, 167, 232, 72, 46, 63, 46, 64],
I = 4624703335380330270,
A = '0x402e3f2e48e8a71e'.
```
No byte level operations in Prolog; takes less than 2usec on my 6 year old laptop.

Variations:
```
?- protobufs:float64_codes(15.1234,Codes), protobufs:int64_codes(I,Codes), format(string(S),"0x~16R",I).
Codes = [30, 167, 232, 72, 46, 63, 46, 64],
I = 4624703335380330270,
S = "0x402E3F2E48E8A71E".

?- protobufs:float64_codes(15.1234,Codes), protobufs:int64_codes(I,Codes), format(string(S),"0b~2r",I).
Codes = [30, 167, 232, 72, 46, 63, 46, 64],
I = 4624703335380330270,
S = "0b100000000101110001111110010111001001000111010001010011100011110".
```

Reverse mapping:
```
?- read_term_from_atom("0x402E3F2E48E8A71E",I,[]),  protobufs:int64_codes(I,Codes), protobufs:float64_codes(F,Codes).
I = 4624703335380330270,
Codes = [30, 167, 232, 72, 46, 63, 46, 64],
F = 15.1234.
```

**Comment by yoquierotacob** [comment] 2022-02-01 10:06
Thanks Jan for the  alternative  solution!   ffilib seems like a really useful package more generally as well,  so  I'll  hide it away in my bag of tricks for later.

**Comment by JanWielemaker** [comment] 2023-04-19 15:12
Closing as resolved.

**Closed by JanWielemaker** 2023-04-19 15:12 UTC

**Comment by kamahen** [comment] 2023-04-19 17:36
@ridgeworks  - `protobufs:float64_codes/2` is currently commented out "exports" list of `protobufs` ... if you think it's useful to add it back to the interface, I can do that. I only removed it because there's no point in making something public if nobody is using it. (Similar for the other functions that give access to the machine representation - these days IEEE is more-or-less universal)

**Comment by ridgeworks** [comment] 2023-04-19 23:59
@kamahen - Perhaps a compromise is to expose the *`_codes` predicates for SWIP native types, i.e. `float64`' and `int64`, including  the `*_when` variations.  I haven't got a good use case but it might save somebody who does from having to write C implementations.

**Comment by kamahen** [comment] 2023-04-20 03:53
Protobufs encode ints as little-endian, so if we change the names to int32_little_endian_codes/2, float64_ieee_codes/2, etc. then it would be clear what they do. (Also, int64_zigzag/2 should become int64_zigzag_little_endian/2, I suppose. The full list are commented out here: https://github.com/SWI-Prolog/contrib-protobufs/blob/master/protobufs.pl#L43

Given the general nature of these conversion predicates, it might be a good idea to make a separate module, but for now `library(protobufs)` isn't the worst place to have them (just not obvious, for someone looking for such predicates).

**Comment by JanWielemaker** [comment] 2023-04-20 08:06
As I see it, there are many wire encodings for transferring primitive data as well as data structures.    We could try to assemble a library that implements most of these and keep adding more as it is used for new projects.    One can also use Prolog for some of the tasks and the `ffi` pack for others (e.g., get the byte representations of floats).

I don't see that much point.   If you want to make a good and high performance implementation for some serialization format you typically better write some of the low-level stuff in C.   It is not a lot of work and you can combine building blocks that you find in many similar projects for (SWI-)Prolog or other languages.

Generally better ways to distribute extensions that involve C(++) are more attractive.   Systems like R and Python got a long way there.
